// ADD_ITEMS
export const ADD_CARTITEMS = "CARTITEMS";
export const ADD_CARTITEMS_FAIL = "CARTITEMS_FAIL";
export const ADD_CARTITEMS_SUCCESS = "CARTITEMS_SUCCESS";
export const EMPTY_CART = "EMPTY_CART";

export const ADD_TODO = 'ADD_TODO';
export const DELETE_TODO = 'DELETE_TODO';